### ISSUE TITLE
TO-DO Improvements

### ISSUE THREAD

**Issue by pedrofran12** [pedrofran12/pim_dm#2]
This issue lists some ideas and future improvements that could be performed to PIM-DM implementation.
- [ ] BFD support
- [ ] IGMPv3
- [ ] IPv6 multicast routing support (update Kernel and implement MLD)
- [ ] Better debug messages
- [ ] More automation on tests
